### ISSUE TITLE
random crash in world

### ISSUE THREAD

**Issue by hazerddex** [Alex-the-666/AlexsMobs#155]
---- Minecraft Crash Report ----
// My bad.

Time: 1/31/21 9:37 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.alexsmobs.event.ServerEvents.onLootLevelEvent(ServerEvents.java:102) ~[?:1.5.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_52_ServerEvents_onLootLevelEvent_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:382) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:375) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$10(Predicate.java:69) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.function.Predicate$$Lambda$491/1322341191.test(Unknown Source) ~[?:?] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:classloading}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[?:4.0.3+3] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1253) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:classloading}
	at com.minecraftabnormals.upgrade_aquatic.common.entities.pike.PikeEntity.generateFishingLoot(PikeEntity.java:447) ~[?:3.0.1] {re:classloading}
	at com.minecraftabnormals.upgrade_aquatic.common.entities.pike.PikeEntity.func_70636_d(PikeEntity.java:208) ~[?:3.0.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.LivingEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldCooldownMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldPreferredSlotMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$24801/886686303.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$23810/1981642575.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.alexsmobs.event.ServerEvents.onLootLevelEvent(ServerEvents.java:102) ~[?:1.5.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_52_ServerEvents_onLootLevelEvent_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:382) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:375) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$10(Predicate.java:69) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.function.Predicate$$Lambda$491/1322341191.test(Unknown Source) ~[?:?] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:classloading}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[?:4.0.3+3] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1253) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:classloading}
	at com.minecraftabnormals.upgrade_aquatic.common.entities.pike.PikeEntity.generateFishingLoot(PikeEntity.java:447) ~[?:3.0.1] {re:classloading}
	at com.minecraftabnormals.upgrade_aquatic.common.entities.pike.PikeEntity.func_70636_d(PikeEntity.java:208) ~[?:3.0.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.LivingEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldCooldownMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldPreferredSlotMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$24801/886686303.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: upgrade_aquatic:pike (com.minecraftabnormals.upgrade_aquatic.common.entities.pike.PikeEntity)
	Entity ID: 3788
	Entity Name: Pike
	Entity's Exact location: 108.78, 59.37, -246.58
	Entity's Block location: World: (108,59,-247), Chunk: (at 12,3,9 in 6,-16; contains blocks 96,0,-256 to 111,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.01, 0.07, -0.08
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['hazerddex'/3175, l='ServerWorld minecraft:overworld New World', x=89.70, y=37.00, z=-265.31]]
	Chunk stats: ServerChunkCache: 2324
	Level dimension: minecraft:overworld
	Level spawn location: World: (89,37,-262), Chunk: (at 9,2,10 in 5,-17; contains blocks 80,0,-272 to 95,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 971 game time, 971 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 67390 (now: false), thunder time: 66310 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$23810/1981642575.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3115147072 bytes (2970 MB) / 6375342080 bytes (6080 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.36.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.36
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |DONE      |NOSIGNATURE
		GokiStats-1.16.3-1.2.13.jar                       |Goki Stats                    |gokistats                     |1.2.13              |DONE      |NOSIGNATURE
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |DONE      |45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		flesh2leather-1.0.2.jar                           |Flesh2Leather                 |flesh2leather                 |1.0.2               |DONE      |NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |DONE      |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |DONE      |NOSIGNATURE
		mining-helmet-1.16.4-2.0.0.jar                    |Mining Helmet                 |mining_helmet                 |2.0.0               |DONE      |NOSIGNATURE
		infernal-expansion-forge-1.3.jar                  |Infernal Expansion            |infernalexp                   |Release 1.3         |DONE      |NOSIGNATURE
		ElenaiDodge-1.16.2-1.7.2.jar                      |Elenai Dodge                  |elenaidodge                   |1.16.2-1.7.2        |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		Druidcraft-1.16.5-0.4.52.jar                      |Druidcraft                    |druidcraft                    |0.4.52              |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar      |Forge Endertech               |forgeendertech                |7.0.9.0             |DONE      |NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.5.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.5.0               |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.88-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.87     |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-3.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-3      |DONE      |NOSIGNATURE
		OuterEnd-0.2.4.jar                                |Outer End                     |outer_end                     |0.2.4               |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.4-10.1.0.jar               |Better Animals Plus           |betteranimalsplus             |10.1.0              |DONE      |NOSIGNATURE
		sophisticatedbackpacks-1.16.4-1.3.4.136.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.4-1.3.4.136    |DONE      |NOSIGNATURE
		simpleplanes-1.16.3-3.2.0.3.jar                   |Simple Planes                 |simpleplanes                  |1.16.3-3.2.0.3      |DONE      |NOSIGNATURE
		mahoutsukai-1.16.5-v1.27.9.jar                    |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.27.9      |DONE      |NOSIGNATURE
		iceandfire-2.1.5-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |DONE      |NOSIGNATURE
		Neverdark-1.0.3.5.jar                             |Neverdark: Legends            |neverdark                     |1.0.3               |DONE      |NOSIGNATURE
		walljump-forge-1.16.4-1.3.6.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.6        |DONE      |NOSIGNATURE
		immersive-portals-0.14-mc1.16.4-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |DONE      |NOSIGNATURE
		mysticalworld-1.16.4-0.3.1.6.jar                  |Mystical World                |mysticalworld                 |1.16.4-0.3.1.6      |DONE      |NOSIGNATURE
		ImmersivePetroleum-1.16.4-3.1.0-2.jar             |Immersive Petroleum           |immersivepetroleum            |3.1.0-2             |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.36-universal.jar                |Forge                         |forge                         |35.1.36             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |DONE      |NOSIGNATURE
		neapolitan-1.16.4-2.0.1.jar                       |Neapolitan                    |neapolitan                    |2.0.1               |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.8.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.8      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		infernalmobs-1.16.2.1.jar                         |Infernal Mobs                 |infernalmobs                  |1.16.2.1            |DONE      |NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |DONE      |NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.36-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		repurposed_structures-1.16.4-2.3.4.jar            |Repurposed Structures         |repurposed_structures         |1.16.4-2.3.4        |DONE      |NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |DONE      |NOSIGNATURE
		Psi+1.16-91.jar                                   |Psi                           |psi                           |1.16-91             |DONE      |NOSIGNATURE
		mana-and-artifice-1.2.1.9.jar                     |Mana and Artifice             |mana-and-artifice             |1.2.1.8             |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		SilentLib-1.16.3-4.9.1+64.jar                     |Silent Lib                    |silentlib                     |4.9.1+64            |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.430-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.430   |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |NOSIGNATURE
		forbidden_arcanus-1.16.4-1.0.0.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.16.4-1.0.0        |DONE      |NOSIGNATURE
		AdLods-1.16.4-4.1.3.0-build.0034.jar              |Large Ore Deposits            |adlods                        |4.1.3.0             |DONE      |NOSIGNATURE
		Undergarden-Tetra+Patch-1.1.1.jar                 |Undergarden/Tetra Patch       |undergardenpatch              |1.1.1               |DONE      |NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.0.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |NOSIGNATURE
		CNB-1.16.3_4-1.2.9.1.jar                          |Creatures and Beasts          |cnb                           |1.2.9.1             |DONE      |NOSIGNATURE
		gaiadimension-1.16.4-1.3.1.jar                    |The Gaia Dimension            |gaiadimension                 |1.3.1               |DONE      |NOSIGNATURE
		evolved_RPG_1.16.4_v0.2.1.jar                     |Evolved RPG                   |evolved_rpg                   |0.2.0               |DONE      |NOSIGNATURE
		whisperwoods-1.16.4-2.0.0.jar                     |Whisperwoods                  |whisperwoods                  |2.0.0               |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.5.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.5      |DONE      |NOSIGNATURE
		tetra-1.16.4-3.6.0.jar                            |Tetra                         |tetra                         |3.6.0               |DONE      |NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		rats-7.1.0-1.16.5.jar                             |Rats                          |rats                          |7.1.0               |DONE      |NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |DONE      |NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.1.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |NOSIGNATURE
		autumnity-1.16.4-2.0.1.jar                        |Autumnity                     |autumnity                     |2.0.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		AkashicTome-1.4-15.jar                            |Akashic Tome                  |akashictome                   |1.4-15              |DONE      |NOSIGNATURE
		tombstone-1.16-6.2.5.jar                          |Corail Tombstone              |tombstone                     |1.16-6.2.5          |DONE      |NOSIGNATURE
		TheAbyss2+1.0.6-8+1.16.4.jar                      |TheAbyss                      |theabyss                      |1.0.6-8             |DONE      |NOSIGNATURE
		psipherals-1.4.0.jar                              |Psionic Peripherals           |psipherals                    |version             |DONE      |NOSIGNATURE
		engineersdecor-1.16.4-1.1.6.jar                   |Engineer's Decor              |engineersdecor                |1.1.6               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		occultism-1.16.5-1.0.9.jar                        |Occultism                     |occultism                     |1.16.5-1.0.9        |DONE      |NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		productivebees-1.16.5-0.5.2.11.jar                |Productive Bees               |productivebees                |1.16.5-0.5.2.11     |DONE      |NOSIGNATURE
		enhancedcelestials-1.0-1.16.4.jar                 |Enhanced Celestials           |enhancedcelestials            |1.0-1.16.4          |DONE      |NOSIGNATURE
		The_Undergarden-1.16.5-0.4.5.jar                  |The Undergarden               |undergarden                   |0.4.5               |DONE      |NOSIGNATURE
		byg-1.1.8.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.8               |DONE      |NOSIGNATURE
		Aquaculture-1.16.4-2.1.12.jar                     |Aquaculture 2                 |aquaculture                   |1.16.4-2.1.12       |DONE      |NOSIGNATURE
		the_bumblezone-1.16.5-2.2.11.jar                  |The Bumblezone                |the_bumblezone                |1.16.5-2.2.11       |DONE      |NOSIGNATURE
		SilentGems-1.16.3-3.7.9+112.jar                   |Silent's Gems 3               |silentgems                    |3.7.9+112           |DONE      |NOSIGNATURE
		ScalingHealth-1.16.4-4.0.3+3.jar                  |Scaling Health                |scalinghealth                 |4.0.3+3             |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		magipsi-1.16.4-2.0.0.0.jar                        |Magical Psi                   |magipsi                       |1.16.4-2.0.0.0      |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.9.jar                   |GeckoLib                      |geckolib3                     |3.0.9               |DONE      |NOSIGNATURE
	Crash Report UUID: 36f82f1e-d109-484c-8715-18dee1a1a54b
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['hazerddex'/3175, l='ServerWorld minecraft:overworld New World', x=89.70, y=37.00, z=-265.31]]
	Data Packs: vanilla, mod:savemystronghold, mod:gokistats, mod:astralsorcery, mod:flesh2leather (incompatible), mod:pamhc2trees (incompatible), mod:wyrmroost (incompatible), mod:mining_helmet (incompatible), mod:infernalexp (incompatible), mod:elenaidodge, mod:jei, mod:druidcraft (incompatible), mod:abnormals_core, mod:buzzier_bees, mod:create (incompatible), mod:bettercaves (incompatible), mod:waystones (incompatible), mod:forgeendertech, mod:mgui (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:sereneseasons, mod:yungsapi, mod:outer_end, mod:betteranimalsplus (incompatible), mod:sophisticatedbackpacks, mod:simpleplanes (incompatible), mod:mahoutsukai (incompatible), mod:iceandfire (incompatible), mod:neverdark, mod:walljump (incompatible), mod:immersive_portals (incompatible), mod:mysticalworld (incompatible), mod:immersivepetroleum (incompatible), mod:forge, mod:bloodmagic, mod:neapolitan, mod:dsurround, mod:infernalmobs (incompatible), mod:antiqueatlas, mod:chocolate, mod:upgrade_aquatic, mod:endergetic, mod:repurposed_structures, mod:pandoras_creatures (incompatible), mod:psi (incompatible), mod:mana-and-artifice, mod:immersiveengineering (incompatible), mod:silentlib (incompatible), mod:biomesoplenty, mod:valhelsia_structures (incompatible), mod:pamhc2crops (incompatible), mod:forbidden_arcanus (incompatible), mod:adlods, mod:undergardenpatch, mod:towers_of_the_wild, mod:atmospheric, mod:pamhc2foodextended (incompatible), mod:cnb, mod:gaiadimension (incompatible), mod:evolved_rpg, mod:whisperwoods (incompatible), mod:curios, mod:tetra, mod:eidolon, mod:savageandravage, mod:patchouli (incompatible), mod:rats, mod:ratlantis, mod:pamhc2foodcore (incompatible), mod:autumnity, mod:autoreglib (incompatible), mod:akashictome, mod:tombstone, mod:theabyss, mod:psipherals (incompatible), mod:engineersdecor, mod:occultism, mod:observerlib, mod:productivebees (incompatible), mod:enhancedcelestials, mod:undergarden, mod:byg, mod:aquaculture (incompatible), mod:the_bumblezone, mod:silentgems, mod:scalinghealth, mod:bettermineshafts (incompatible), mod:magipsi, mod:geckolib3 (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
[crash-2021-01-31_21.37.51-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/5902052/crash-2021-01-31_21.37.51-server.txt)

**Comment by Alex-the-666** [comment]
fixed

**Comment by recklessrider** [comment]
Did you release a new version? I can confirm this still happens as of yesterday 2/7
