### ISSUE TITLE
Disappearing Terrapin Turtles

### ISSUE THREAD

**Issue by PatataLlama** [Alex-the-666/AlexsMobs#961]
My friend and I play on 1.18 and have been trying to keep some terrapin turtles. We pick them up in the buckets and then put them down where they cannot get out and also name them but even then they despawn after a short while. It has happened multiple times now, not sure if that is supposed to happen or not.

**Comment by cech12** [comment]
This should be fixed in Alex's Mobs 1.17.0. Are you using this version?

**Comment by PatataLlama** [comment]
Sorry, not to be rude but I did state that we use the 1.18 version. So does that mean it is not fixed for that version?

**Comment by cech12** [comment]
I meant the Alex's Mobs version 1.17.0

You did not say which mod version you are using. :)

As far as I can see, the mentioned bug should be fixed since Alex's Mobs 1.17.0 for Minecraft 1.18+

**Comment by PatataLlama** [comment]
SorrySorry, that's my bad. 
I assumed it was 1.18 but I just looked and it is 1.17.1

**Comment by cech12** [comment]
Ok that is weird.^^ Maybe my PR #955 can fix this issue :)

**Comment by cech12** [comment]
Ah ok, I found out where the issue comes from. The "FromBucket" value is set to true here https://github.com/Alex-the-666/AlexsMobs/commit/279eb89da75756998bd7c8e3fb9339529c764699 (since 1.17.0) but 3 lines later it is overridden by the entity data and is resetted to false. ^^

My PR #955 fixes this issue by using the vanilla logic.
